import("//webrtc.gni")

rtc_executable("minimal_peerconnection") {
  
  testonly = true
  sources = [
    "minimal_peerconnection.cc",
    "console.cc",
    "file_transfer_handler.cc",
    "file_transfer_state_machine.cc",
  ]

  deps = [
    "//api:create_peerconnection_factory",
    "//api:libjingle_peerconnection_api",
    "//api:rtc_error",
    "//api:make_ref_counted",
    "//api:media_stream_interface",
    "//api:scoped_refptr",


    "//api/environment:environment_factory",

    "//media:media_engine",

    "//media:media_channel",

    "//p2p:connection",
    "//p2p:port_allocator",

    "//pc:libjingle_peerconnection",

    "//rtc_base:async_dns_resolver",
    "//rtc_base:checks",
    "//rtc_base:logging",
    "//rtc_base:net_helpers",
    "//rtc_base:refcount",
    "//rtc_base:rtc_certificate_generator",
    "//rtc_base:stringutils",
    "//rtc_base/third_party/sigslot",

    "//system_wrappers",

    "//test:test_support",
    "//test:frame_generator_capturer",
    "//test:rtp_test_utils",

    "//third_party/abseil-cpp/absl/base:nullability",
    "//third_party/abseil-cpp/absl/memory",
    "//third_party/jsoncpp",
  ]

}